# Generated by Django 4.2.4 on 2023-08-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('Company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
    ]
