# Generated by Django 4.2.4 on 2023-08-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_company_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
