# Generated by Django 4.2.4 on 2023-08-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='userId',
            field=models.CharField(max_length=100),
        ),
    ]
